### environment: dev

GET {{Cs_backend_HostAddress}}/courses/
Accept: application/json

###

POST {{Cs_backend_HostAddress}}/courses/
Content-Type: application/json

{
  "courseId": 1,
  "name": "Test3"
}

###

GET {{Cs_backend_HostAddress}}/courses/
Accept: application/json

##