### environment: dev

@Cs_backend_HostAddress = http://localhost:5249

GET {{Cs_backend_HostAddress}}/groups/1
Accept: application/json

###

POST {{Cs_backend_HostAddress}}/groups/1
Content-Type: application/json

{
  "studentId": 0,
  "name": "Test",
  "groupId": 1,
  "tgUserName": "Test",
  "courseId": 1
}

###

GET {{Cs_backend_HostAddress}}/groups/1
Accept: application/json

###